# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Run test cases
      env:
        TEST_DB_NAME: ${{secrets.TEST_DB_NAME}}
        DB_NAME: ${{secrets.DB_NAME}}
        DB_USER: ${{secrets.DB_USER}}
        DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        DB_HOST: ${{secrets.DB_HOST}}
        DB_PORT: ${{secrets.DB_PORT}}
        ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
        REFRESH_TOKEN_SECRET: ${{secrets.REFRESH_TOKEN_SECRET}}
      run: npm test
